version: '2.3'
services:
  animaniacs:
    image: fabianonunes/animaniacs:2.0.0
    environment:
      GIN_MODE: release
    ports:
      - 3000:3000
    build:
      context: .
      args:
        http_proxy: ${PROXY}
        https_proxy: ${PROXY}
